const express = require('express')
const ControllerExercicio = require('../controllers/exercicio')

const controller = new ControllerExercicio()
const router = express.Router()
router.post('/api/exercicio1', controller.Somar)
router.post('/api/exercicio2', controller.Multiplicar)
router.post('/api/exercicio3', controller.Media5)
router.post('/api/exercicio4', controller.Celsiofahrenheit)
router.post('/api/exercicio5', controller.Quilometrosmilha)
router.post('/api/exercicio6', controller.Segundorelogio)
router.post('/api/exercicio7', controller.Quilometrosmetros)
router.post('/api/exercicio8', controller.Tabuada1a10)
router.post('/api/exercicio9', controller.Aprovado)
router.post('/api/exercicio10', controller.Imc)
module.exports = router